### ISSUE TITLE
Minimal cordova-ios version is a bit too high

### ISSUE THREAD

**Issue by andrehtissot** [andrehtissot/cordova-plugin-fcm-with-dependecy-updated#96]
I tryed to install 

WARN: Install the FCM plugin: 'ionic cordova plugin add cordova-plugin-fcm-with-dependecy-updated'

But on ionic cordova plugin list 

cordova-plugin-android-permissions 1.0.2 "Permissions"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-document-viewer 0.9.13 "SitewaertsDocumentViewer"
cordova-plugin-fcm-with-dependecy-updated 6.4.2 "Cordova FCM Push Plugin"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 5.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.6.4 "SocialSharing"
cordova-sqlite-storage 5.0.0 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
es6-promise-plugin 4.2.2 "Promise"

And when i Tryed to install again:
Plugin doesn't support this project's cordova-ios version. cordova-ios: 5.1.0, failed version requirement: >=5.1.1

Is in there. 

cordova-ios 5.1.0

_Originally posted by @Nogatz in https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated/issues/92#issuecomment-640572447_

**Comment by andrehtissot** [comment]
Fixed on v6.4.3 (and v7.0.0-beta.2)

**Comment by Nogatz** [comment]
I Tryed both but still cant do it work.

Do you have a repository that I can test?

Or I have cocoapods sudo error or Firebase.h file not found.

**Comment by Nogatz** [comment]
Just to complement.

And the instalation with cocoapods its a nightmare. 
First the sudo problem, later paths problems.

Danm Apple changing the wheels with the car in the road.

**Comment by andrehtissot** [comment]
I recommend you to try to clone and run https://github.com/andrehtissot/cordova-plugin-fcm-with-dependecy-updated-app-example which, although being pure cordova, it should install with cocoapods easily.

**Comment by andrehtissot** [comment]
Issue closed due to inactivity.
